version: "3"
services:
  app:
    container_name: food-delivery-sample
    restart: always
    image: vladimirfomene/food-delivery-sample
    ports:
      - 3000:8080
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
